default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mtg_deck_builder_development

test:
  <<: *default
  database: mtg_deck_builder_test

production:
  <<: *default
  password: <%= ENV['MTG_DECK_BUILDER_DATABASE_PASSWORD'] %>
